# Copyright (c) 2019 Mathieu-André Chiasson
# All rights reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

git:
  quiet: true
  depth: 1

language: generic

matrix:
  include:

    - os: osx
      env: TOOLCHAIN=osx-10.13.cmake

    - os: linux
      sudo: required
      compiler: 'clang-3.5'
      env: TOOLCHAIN=clang-3.5.cmake
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.5
          packages:
            - ninja-build
            - clang-3.5

    - os: linux
      sudo: required
      compiler: 'clang-6.0'
      env: TOOLCHAIN=clang-6.0.cmake
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
          packages:
            - ninja-build
            - clang-6.0

    - os: linux
      sudo: required
      compiler: 'gcc-4.8'
      env: TOOLCHAIN=gcc-4.8.cmake
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - ninja-build
            - gcc-4.8
            - g++-4.8

    - os: linux
      compiler: 'gcc-7'
      env: TOOLCHAIN=gcc-7.cmake
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - ninja-build
            - gcc-7
            - g++-7

script:
  - ./ci/build-${TRAVIS_OS_NAME}.sh ${TOOLCHAIN}
